name: Development
on:
   workflow_call:
   workflow_dispatch:
   push:
      branches-ignore:
        - main
jobs:
   test:
      name: Lint and Test
      uses: uicpharm/workflows/.github/workflows/lint-and-test.yml@v1
