name: Deploy Documentation
on:
   workflow_call:
   workflow_dispatch:
   push:
      branches:
         - main
jobs:
   test:
      name: Test
      uses: uicpharm/workflows/.github/workflows/lint-and-test.yml@v1

   deploy:
      name: Deploy
      needs: test
      runs-on: ubuntu-latest
      permissions:
         contents: read
         pages: write
         id-token: write
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}
      steps:
         - uses: actions/checkout@v6
         - uses: uicpharm/workflows/actions/setup-and-install@v1
         - run: npm run build
         - uses: actions/configure-pages@v6
         - uses: actions/upload-pages-artifact@v5
           with: { path: 'docs/.vitepress/dist' }
         - name: Deploy
           id: deployment
           uses: actions/deploy-pages@v5
